<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="5" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="61" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="61" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
      <class name="com.revature.tests.dal.PersonDAOTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.revature.tests.dal.PersonDAOTests@17579e0f]" name="setup" is-config="true" duration-ms="11" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="personDoesNotExist()[pri:0, instance:com.revature.tests.dal.PersonDAOTests@17579e0f]" name="personDoesNotExist" duration-ms="4" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- personDoesNotExist -->
        <test-method status="PASS" signature="createPersonSuccess()[pri:1, instance:com.revature.tests.dal.PersonDAOTests@17579e0f]" name="createPersonSuccess" duration-ms="1" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPersonSuccess -->
        <test-method status="PASS" signature="getPersonSuccess()[pri:0, instance:com.revature.tests.dal.PersonDAOTests@17579e0f]" name="getPersonSuccess" duration-ms="0" started-at="2022-04-26T10:49:10 EDT" depends-on-methods="com.revature.tests.dal.PersonDAOTests.createPersonSuccess" finished-at="2022-04-26T10:49:10 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPersonSuccess -->
      </class> <!-- com.revature.tests.dal.PersonDAOTests -->
      <class name="com.revature.tests.sl.PersonServiceTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.revature.tests.sl.PersonServiceTests@646d64ab]" name="setup" is-config="true" duration-ms="2" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="noDerek()[pri:0, instance:com.revature.tests.sl.PersonServiceTests@646d64ab]" name="noDerek" duration-ms="0" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
          <exception class="com.revature.custom_exception.NoDerrek">
            <message>
              <![CDATA[No Derreks allowed!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.revature.custom_exception.NoDerrek: No Derreks allowed!
at com.revature.sl.PersonServiceImp.serviceCreatePerson(PersonServiceImp.java:30)
at com.revature.tests.sl.PersonServiceTests.noDerek(PersonServiceTests.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- com.revature.custom_exception.NoDerrek -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noDerek -->
        <test-method status="PASS" signature="personNotFound()[pri:0, instance:com.revature.tests.sl.PersonServiceTests@646d64ab]" name="personNotFound" duration-ms="0" started-at="2022-04-26T10:49:10 EDT" finished-at="2022-04-26T10:49:10 EDT">
          <exception class="com.revature.custom_exception.PersonNotFound">
            <message>
              <![CDATA[Could not find the person]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.revature.custom_exception.PersonNotFound: Could not find the person
at com.revature.sl.PersonServiceImp.serviceGetPerson(PersonServiceImp.java:41)
at com.revature.tests.sl.PersonServiceTests.personNotFound(PersonServiceTests.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- com.revature.custom_exception.PersonNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- personNotFound -->
      </class> <!-- com.revature.tests.sl.PersonServiceTests -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
